updates

diff --git a/.sdlc/build b/.sdlc/build
--- a/.sdlc/build
+++ b/.sdlc/build
@@ -4,10 +4,10 @@ set -e
 
 TOOL_SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
-HACK_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
-PRJ_HOME="$( cd -P "$( dirname "$HACK_DIR" )" && pwd )"
+SDLC_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
+PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"
 
-source "${HACK_DIR}/config"
+source "${SDLC_DIR}/config"
 
 CMDS_DIR="${PRJ_HOME}/cmd"
 BIN_DIR="${PRJ_HOME}/bin"
@@ -25,7 +25,12 @@ echo "version : ${APP_VERSION}"
 echo "git : ${git_commit}"
 echo "build time : ${buildtime}"
 
-dep ensure
+command -v dep >/dev/null || {
+  echo "dep not found"
+  exit 1
+}
+echo 'Running dep ensure'
+dep ensure -v
 
 for dir in $(find "$CMDS_DIR" -mindepth 1 -maxdepth 1 -type d); do
   app_name=$(basename "$dir")
