sdlc scripts

diff --git a/.sdlc/build-dist b/.sdlc/build-dist
--- a/.sdlc/build-dist
+++ b/.sdlc/build-dist
@@ -21,8 +21,8 @@ echo "git : ${git_commit}"
 echo "build time : ${buildtime}"
 
 [[ -z "$DIST_DIR" ]] && {
-    echo "no dist dir set"
-    exit 1
+  echo "no dist dir set"
+  exit 1
 }
 
 [[ -d "${PRJ_HOME}/bin" ]] && rm -r "${PRJ_HOME}/bin"
@@ -32,40 +32,40 @@ mkdir -p "$DIST_DIR"
 platforms="windows/amd64 linux/amd64 darwin/amd64"
 
 for dir in $(find "$CMDS_DIR" -mindepth 1 -maxdepth 1 -type d); do
-	app_name=$(basename "$dir")
-    echo " =====     Process ${app_name} ${dir}     ====="
-    for platform in $platforms; do
-        cd "$PRJ_HOME"
-        target_goos=$(echo $platform | cut -d/ -f1)
-        target_goarch=$(echo $platform | cut -d/ -f2)
-        echo "building for ${target_goos} ${target_goarch}"
-        platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
-        platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
-        mkdir -p "$platform_dist_dir"
-        ext=''
-        [[ "windows" = "$target_goos" ]] && ext='.exe'
-        built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
-        GOOS="$target_goos" GOARCH="$target_goarch" go build -ldflags "-s \
-      -X main.version=${APP_VERSION} \
-      -X main.buildTime=${buildtime} \
-      -X main.gitCommit=${git_commit}" \
-      -o "$built" \
-      "github.com/${GH_OWNER}/${GH_REPO}/cmd/${app_name}"
-        [[ -e "$built" ]] || {
-            echo "expected file not found: ${built}"
-            exit 1
-        }
-        mv "${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}" "${platform_dist_dir}/${app_name}${ext}"
-        # cd "$DIST_DIR"
-        # zip -r "${platform_dist_basename}.zip" "$platform_dist_basename"
-        # rm -r "$platform_dist_basename"
-    done
+  app_name=$(basename "$dir")
+  echo " =====     Process ${app_name} ${dir}     ====="
+  for platform in $platforms; do
+    cd "$PRJ_HOME"
+    target_goos=$(echo $platform | cut -d/ -f1)
+    target_goarch=$(echo $platform | cut -d/ -f2)
+    echo "building for ${target_goos} ${target_goarch}"
+    platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
+    platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
+    mkdir -p "$platform_dist_dir"
+    ext=''
+    [[ "windows" = "$target_goos" ]] && ext='.exe'
+    built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
+    GOOS="$target_goos" GOARCH="$target_goarch" go build -ldflags "-s \
+    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.version=${APP_VERSION} \
+    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.buildTime=${buildtime} \
+    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.gitCommit=${git_commit}" \
+    -o "$built" \
+    "github.com/${GH_OWNER}/${GH_REPO}/cmd/${app_name}"
+    [[ -e "$built" ]] || {
+      echo "expected file not found: ${built}"
+      exit 1
+    }
+    mv "${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}" "${platform_dist_dir}/${app_name}${ext}"
+    # cd "$DIST_DIR"
+    # zip -r "${platform_dist_basename}.zip" "$platform_dist_basename"
+    # rm -r "$platform_dist_basename"
+  done
 done
 
 cd "$DIST_DIR"
 for dir in $(find "$DIST_DIR" -mindepth 1 -maxdepth 1 -type d); do
-	dist_folder=$(basename "$dir")
-    echo " =====     Create dist ${dist_folder} ${dir}     ====="
-    zip -r "${dist_folder}.zip" "$dist_folder"
-    rm -r "$dist_folder"
+  dist_folder=$(basename "$dir")
+  echo " =====     Create dist ${dist_folder} ${dir}     ====="
+  zip -r "${dist_folder}.zip" "$dist_folder"
+  rm -r "$dist_folder"
 done
diff --git a/.sdlc/update b/.sdlc/update
--- a/.sdlc/update
+++ b/.sdlc/update
@@ -10,8 +10,8 @@ PRJ_HOME="$( cd -P "$( dirname "$HACK_DIR" )" && pwd )"
 cd "$PRJ_HOME"
 
 command -v dep >/dev/null || {
-    echo "dep not found"
-    exit 1
+  echo "dep not found"
+  exit 1
 }
 
 dep ensure -update
